# Todo List:
# - Move librpcsx compilation away
# - Do not use legacy CMake scripts (figure out how)name: Build Thor APK

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install packages
        run: yes | sdkmanager "cmake;3.31.6"

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rpcsx-thor-debug-build
          path: app/build/outputs/apk/release/rpcsx-thor-experiment-release.apk
